import type { Metadata } from "next";
import { Inter, Bai_Jamjuree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "sonner";

const BaiJamjuree = Bai_Jamjuree({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="forest" className="h-screen">
      <body className={BaiJamjuree.className + " h-full overflow-hidden"}>
        <Navbar />
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
